""".

Revision ID: 533648b8e37e
Revises: a4a39e4e0081
Create Date: 2022-08-24 18:29:21.649828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533648b8e37e'
down_revision = 'a4a39e4e0081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
